UPLOADFILES:
  script_files:
    REPEAT: '+'
  support_files:
    REPEAT: '*'
  hooks:
    REPEAT: '?'

METADATA:
  REPEAT+:
    runnable_group:
      REPEAT+:
        script_file_path: 
          TEXT_MATCHER: .+
    enable_feedback_file_hook:
      OPTIONS:
        - true
        - false
    feedback_file:
      TEXT_MATCHER: .*
    test_timeout: 
      TEXT_MATCHER: \d+
      DEFAULT: "10"
    test_cases:
      TEXT_MATCHER: \d+
      DEFAULT: "100"
    points:
      {}
