version: 2
updates:
  - package-ecosystem: pip
    directory: "/client"
    schedule:
      interval: "monthly"
  - package-ecosystem: pip
    directory: "/server"
    schedule:
      interval: "monthly"
