dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install pytest
  - pip install hypothesis
  - pip install -r server/bin/requirements.txt
# command to run tests
script:
  - pytest --ignore testers/testers/py/tests
