dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -U pytest hypothesis fakeredis .
# command to run tests
script:
  - pytest --ignore src/autotester/testers/py/tests
