workspace: !ENV ${HOME}/.autotesting/workspace

server_user: !ENV ${USER}

workers:
  - users:
      - name: !ENV ${USER}
        reaper: null
    queues:
      - high
      - low
      - batch

redis:
  url: redis://127.0.0.1:6379/0

supervisor:
  url: '127.0.0.1:9001'

rlimit_settings:
  nproc:
    - 300
    - 300

resources:
  port:
    min: 50000
    max: 65535
  postgresql:
    port: 5432
    host: localhost
