workspace: !ENV ${HOME}/.markus-autotesting/

redis:
  url: !ENV ${REDIS_URL}

users:
  server:
    name: !ENV ${USER}
  workers:
    - name: !ENV ${USER}
      reaper: null

resources:
  postgresql:
    database: !ENV ${PGDATABASE}
    password: !ENV ${PGPASSWORD}
    host: !ENV ${PGHOST}