workspace: !ENV ${HOME}/.markus-autotesting/

redis:
  url: !ENV ${REDIS_URL}

users:
  server:
    name: !ENV ${USER}
  workers:
    - name: !ENV ${USER}
      reaper: null

resources:
  postgresql:
    port: !ENV ${PGPORT}
    host: !ENV ${PGHOST}