# Default settings.
# Settings prefixed with an underscore are technically overwritable by
# a local settings file but it is not recommended.

server_user: !ENV ${USER}

workspace: !ENV ${HOME}/.markus-autotesting/

workers:
  - users:
      - name: !ENV ${USER}
        reaper: null
    queues:
      - high
      - low
      - batch

redis:
  url: 'redis://127.0.0.1:6379/0'
  _prefix: 'redis:'
  _current_test_script_hash: current_test_scripts
  _pop_interval_hash: pop_interval

supervisor:
  url: '127.0.0.1:9001'

rlimit_settings:
  nproc:
    - 300
    - 300

resources:
  port:
    _redis_int: port
    min: 50000
    max: 65535
  postgresql:
    _prefix: autotest_
    port: 5432
    host: localhost

_workspace_contents:
  _scripts: scripts
  _results: results
  _specs: specs
  _logs: logs
  _workers: workers
  _default_venv_name: defaultvenv
  _settings_file: settings.json
  _files_dir: files
  _hooks_file: hooks.py
