workspace: !ENV ${AUTOTESTER_WORKSPACE}

redis:
  url: !ENV ${REDIS_URL}

server_user: !ENV ${AUTOTESTER_SERVER_USER}

supervisor:
  url: !ENV ${AUTOTESTER_SUPERVISOR_URL}

resources:
  postgresql:
    port: !ENV ${PGPORT}
    host: !ENV ${PGHOST}
