UPLOADFILES:
  hooks:
    REPEAT: '?'
  pylintrc_file:
    REPEAT: '?'

METADATA:
  tester_type: pyta
  tester_name:
    TEXT_MATCHER: .+
  script_data:
    REPEAT+:
      runnable_group:
        REPEAT+:
          student_file_path: 
            TEXT_MATCHER: .+
      enable_feedback_file_hook:
        OPTIONS:
          - true
          - false 
      enable_annotations_hook:
        OPTIONS:
        - true
        - false
      feedback_file:
        TEXT_MATCHER: .*
      points:
        {}
      config:
        {}
      script_timeout:
        TEXT_MATCHER: \d+
        DEFAULT: "30"
      hooks_file_path:
        TEXT_MATCHER: .*