UPLOADFILES:
  dataset_files:
    REPEAT: '+'
  schema_file:
    REPEAT: '?'
  solution_files:
    REPEAT: '+'

METADATA:
  REPEAT+:
    solution_file_path:
      TEXT_MATCHER: .+
    dataset_files:
      REPEAT+:
        dataset_file_path:
          TEXT_MATCHER: .+
        points:
          TEXT_MATCHER: '\d+'
          DEFAULT: "1"
    order_by:
      TEXT_MATCHER: .*