feedback_file:
  TEXT_MATCHER: .*
enable_feedback_file_hook:
  DEPENDS: feedback_file
  OPTIONS:
    - true
    - false 
hooks:
  TYPE: FILE
  REPEAT: '?'
dataset_files:
  TYPE: FILE
  REPEAT: '+'
schema_file:
  TYPE: FILE
  REPEAT: '?'
solution_files:
  TYPE: FILE
  REPEAT: '+'
  ASSOCIATE: dataset_files
order_by:
  TEXT_MATCHER: .*
  ASSOCIATE: 
    - dataset_files
    - solution_files