workspace: !ENV ${WORKSPACE}
redis_url: !ENV ${REDIS_URL}
supervisor_url: !ENV ${SUPERVISOR_URL}
worker_log_dir: !ENV ${WORKER_LOG_DIR}
workers:
  - user: !ENV ${USER}
    queues:
      - high
      - low
      - batch
  - user: abc
    queues:
      - high
      - low
      - batch
rlimit_settings: # RLIMIT settings (see details below)
  nproc: # for example, this setting sets the hard and soft limits for the number of processes available to 300
    - 300
    - 300