UPLOADFILES:
  dataset_files:
    REPEAT: '+'
  schema_file:
    REPEAT: '1'
  java_class_files:
    REPEAT: '+'

METADATA:
  matrix:
    REPEAT+:
      java_method_name:
        TEXT_MATCHER: .+
      dataset_files:
        REPEAT+:
          dataset_file_path:
            TEXT_MATCHER: .+
          tables:
            REPEAT+:
              table_names:
                TEXT_MATCHER: .*
              points:
                TEXT_MATCHER: '\d+'
                DEFAULT: "1"
      order_by:
        TEXT_MATCHER: .*
  schema_file_path: .+
