UPLOADFILES:
  hooks:
    REPEAT: '?'

METADATA:
  tester_type: jdbc
  tester_name:
    TEXT_MATCHER: .+
  script_data:
    REPEAT+:
      runnable_group:
        REPEAT+:
          solution_file_path: 
            TEXT_MATCHER: .+
          dataset_file_path:
            TEXT_MATCHER: .+
      enable_feedback_file_hook:
        OPTIONS:
          - true
          - false 
      feedback_file:
        TEXT_MATCHER: .*
      script_timeout:
        TEXT_MATCHER: \d+
        DEFAULT: "30"
      hooks_file_path:
        TEXT_MATCHER: .*