name: Autotester tests
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
        test-dir:
          - client
          - server
    name: ${{ matrix.test-dir }} tests with python ${{ matrix.python-version }}
    env:
      AUTOTESTER_CONFIG: server/autotest_server/tests/fixtures/test_config.yml
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install python packages
        run: python -m pip install pytest fakeredis -r ${{ matrix.test-dir }}/requirements.txt
      - name: run tests
        run: pytest ${{ matrix.test-dir }}
