name: Autotester tests
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - 3.11
          - 3.12
          - 3.13
        test-dir:
          - client
          - server
    name: ${{ matrix.test-dir }} tests with python ${{ matrix.python-version }}
    env:
      AUTOTESTER_CONFIG: server/autotest_server/tests/fixtures/test_config.yml
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install python packages
        run: |
          python -m pip install pytest python-dotenv fakeredis typing-extensions nbformat PyPDF2 \
            -r ${{ matrix.test-dir }}/requirements.txt \
            -r server/autotest_server/testers/jupyter/requirements.txt
      - name: Create users
        run: |
          sudo adduser --disabled-login --no-create-home fake_user
          sudo adduser --disabled-login --no-create-home fake_user_2
      - name: run tests
        run: pytest ${{ matrix.test-dir }}
